SELECT A.FLAVOR
FROM FIRST_HALF A
    INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS J_TOTAL
               FROM JULY
               GROUP BY FLAVOR) B
        ON A.FLAVOR = B.FLAVOR
ORDER BY TOTAL_ORDER + J_TOTAL DESC
LIMIT 3