SELECT CHILD.ITEM_ID, CHILD.ITEM_NAME, CHILD.RARITY FROM ITEM_INFO AS PARENT
INNER JOIN ITEM_TREE AS IT ON IT.PARENT_ITEM_ID = PARENT.ITEM_ID
INNER JOIN ITEM_INFO AS CHILD ON CHILD.ITEM_ID = IT.ITEM_ID
WHERE PARENT.RARITY = 'RARE'
ORDER BY CHILD.ITEM_ID DESC